#!/usr/bin/env python3
"""Validate the portable default BlueMagpie-TTS profile and reference audio."""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parents[1]
PROFILE = ROOT / "references" / "bluemagpie-default-voice.json"
ASSEMBLER = REPO_ROOT / "TTS-and-Voice-AI" / "tts-skill" / "scripts" / "assemble_pcm_narration.py"
GENERATOR = ROOT / "scripts" / "generate_bluemagpie_tts.py"
WINDOWS_ABSOLUTE_PATH = re.compile(r"(?i)(?:^|[\"'])(?:[a-z]:[/\\])")


def require(condition: bool, message: str, failures: list[str]) -> None:
    if not condition:
        failures.append(message)


def probe_audio(path: Path) -> dict[str, object]:
    output = subprocess.check_output(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration,size:stream=codec_name,sample_rate,channels:format_tags=prompt",
            "-of",
            "json",
            str(path),
        ],
        text=True,
        encoding="utf-8",
    )
    payload = json.loads(output)
    stream = payload["streams"][0]
    return {
        "codec": stream["codec_name"],
        "sample_rate": int(stream["sample_rate"]),
        "channels": int(stream["channels"]),
        "duration_seconds": float(payload["format"]["duration"]),
        "bytes": int(payload["format"]["size"]),
        "prompt": payload["format"].get("tags", {}).get("prompt"),
    }


def pcm_hash(path: Path, *, start: float | None = None, end: float | None = None) -> str:
    command = ["ffmpeg", "-v", "error"]
    if start is not None:
        command.extend(["-ss", f"{start:.6f}"])
    if end is not None:
        command.extend(["-to", f"{end:.6f}"])
    command.extend(
        [
            "-i",
            str(path),
            "-map_metadata",
            "-1",
            "-ac",
            "1",
            "-ar",
            "48000",
            "-c:a",
            "pcm_s16le",
            "-f",
            "hash",
            "-hash",
            "sha256",
            "-",
        ]
    )
    output = subprocess.check_output(command, text=True, encoding="utf-8").strip()
    return output.removeprefix("SHA256=").lower()


def validate_provenance(
    prompt_text: object, profile: dict[str, object], failures: list[str]
) -> None:
    require(isinstance(prompt_text, str) and bool(prompt_text), "embedded BlueMagpie prompt metadata is missing", failures)
    if not isinstance(prompt_text, str) or not prompt_text:
        return
    try:
        workflow = json.loads(prompt_text)
    except json.JSONDecodeError:
        failures.append("embedded BlueMagpie prompt metadata is invalid JSON")
        return
    provenance = profile.get("reference_provenance", {})
    prefix = provenance.get("source_filename_prefix")
    save_node: dict[str, object] | None = None
    for node in workflow.values():
        if (
            isinstance(node, dict)
            and node.get("class_type") == "SaveAudio"
            and node.get("inputs", {}).get("filename_prefix") == prefix
        ):
            save_node = node
            break
    require(save_node is not None, "embedded prompt does not identify the selected BlueMagpie take", failures)
    if save_node is None:
        return
    audio_link = save_node.get("inputs", {}).get("audio")
    require(isinstance(audio_link, list) and len(audio_link) == 2, "selected SaveAudio link is invalid", failures)
    if not isinstance(audio_link, list) or len(audio_link) != 2:
        return
    tts_node = workflow.get(str(audio_link[0]), {})
    require(tts_node.get("class_type") == provenance.get("generator_node") == "BlueMagpieTTS", "selected source was not generated by BlueMagpieTTS", failures)
    inputs = tts_node.get("inputs", {})
    require(inputs.get("seed") == provenance.get("seed") == 1150797764, "selected source seed is incorrect", failures)
    require(inputs.get("cfg_value") == provenance.get("cfg_value") == 2.0, "selected source CFG is incorrect", failures)
    require(inputs.get("inference_timesteps") == provenance.get("inference_timesteps") == 40, "selected source inference steps are incorrect", failures)
    require(inputs.get("text") == provenance.get("text"), "selected source text does not match its provenance", failures)
    model_link = inputs.get("model")
    require(isinstance(model_link, list) and len(model_link) == 2, "selected source model link is invalid", failures)
    if isinstance(model_link, list) and len(model_link) == 2:
        loader = workflow.get(str(model_link[0]), {})
        require(loader.get("class_type") == "BlueMagpieModelLoader", "selected source loader is not BlueMagpieModelLoader", failures)
        require(loader.get("inputs", {}).get("model_path") == profile.get("model"), "selected source model path is incorrect", failures)


def main() -> int:
    failures: list[str] = []
    raw = PROFILE.read_text(encoding="utf-8")
    profile = json.loads(raw)

    require(not WINDOWS_ABSOLUTE_PATH.search(raw), "profile contains a machine-specific absolute path", failures)
    require(profile.get("provider") == "comfyui-bluemagpie-tts", "BlueMagpie provider is incorrect", failures)
    require(profile.get("voice_id") == "bluemagpie-clone-take07-30s-take05-seed1150797764", "voice ID is incorrect", failures)
    require(profile.get("model") == "OpenFormosa/BlueMagpie-TTS", "BlueMagpie model is incorrect", failures)
    comfyui = profile.get("comfyui", {})
    require(comfyui.get("loader_node") == "BlueMagpieModelLoader", "BlueMagpie loader node is incorrect", failures)
    require(comfyui.get("node") == "BlueMagpieTTS", "BlueMagpie TTS node is incorrect", failures)
    require(comfyui.get("save_node") == "SaveAudio", "BlueMagpie save node is incorrect", failures)
    require(profile.get("reference_mode") == "derived-reference-audio-path", "derived reference-audio-path mode is not selected", failures)

    assets = profile.get("assets", {})
    require(set(assets) == {"source_audio", "cloning_audio"}, "profile must declare source_audio and cloning_audio", failures)
    source_record = assets.get("source_audio", {})
    clone_record = assets.get("cloning_audio", {})
    source_relative = source_record.get("path", "")
    clone_relative = clone_record.get("path", "")
    source_asset = ROOT / source_relative
    clone_asset = ROOT / clone_relative
    require(bool(source_relative) and not Path(source_relative).is_absolute(), "source_audio path must be relative", failures)
    require(bool(clone_relative) and not Path(clone_relative).is_absolute(), "cloning_audio path must be relative", failures)
    require(source_asset.is_file(), "canonical BlueMagpie source is missing", failures)
    require(clone_asset.is_file(), "BlueMagpie runtime reference is missing", failures)

    if source_asset.is_file():
        digest = hashlib.sha256(source_asset.read_bytes()).hexdigest()
        require(digest == source_record.get("sha256"), "source audio SHA-256 mismatch", failures)
        require(source_asset.stat().st_size == source_record.get("bytes"), "source audio byte count mismatch", failures)
        source_info = probe_audio(source_asset)
        expected_source = profile.get("source_audio_format", {})
        require(source_info["codec"] == expected_source.get("codec") == "flac", "source audio must be FLAC", failures)
        require(source_info["channels"] == expected_source.get("channels") == 1, "source audio must be mono", failures)
        require(source_info["sample_rate"] == expected_source.get("sample_rate") == 48000, "source audio must be 48 kHz", failures)
        require(abs(float(source_info["duration_seconds"]) - profile.get("source_audio_duration_seconds", 0)) < 0.001, "source audio duration mismatch", failures)
        validate_provenance(source_info["prompt"], profile, failures)

    if clone_asset.is_file():
        digest = hashlib.sha256(clone_asset.read_bytes()).hexdigest()
        require(digest == clone_record.get("sha256"), "runtime reference SHA-256 mismatch", failures)
        require(clone_asset.stat().st_size == clone_record.get("bytes"), "runtime reference byte count mismatch", failures)
        clone_info = probe_audio(clone_asset)
        expected_clone = profile.get("reference_audio_format", {})
        require(clone_info["codec"] == expected_clone.get("codec") == "flac", "runtime reference must be FLAC", failures)
        require(clone_info["channels"] == expected_clone.get("channels") == 1, "runtime reference must be mono", failures)
        require(clone_info["sample_rate"] == expected_clone.get("sample_rate") == 48000, "runtime reference must be 48 kHz", failures)
        require(abs(float(clone_info["duration_seconds"]) - profile.get("reference_audio_duration_seconds", 0)) < 0.001, "runtime reference duration mismatch", failures)

    derivation = profile.get("reference_derivation", {})
    start = derivation.get("start_seconds")
    end = derivation.get("end_seconds")
    require(derivation.get("source_asset") == "source_audio", "runtime reference derivation source is incorrect", failures)
    require(start == 4.222125 and end == 12.196063, "runtime reference derivation bounds are incorrect", failures)
    require(abs(float(derivation.get("duration_seconds", 0)) - 7.973938) < 0.000001, "runtime reference derivation duration is incorrect", failures)
    if source_asset.is_file() and clone_asset.is_file() and isinstance(start, (int, float)) and isinstance(end, (int, float)):
        require(
            pcm_hash(source_asset, start=float(start), end=float(end)) == pcm_hash(clone_asset),
            "runtime reference PCM does not match the declared source interval",
            failures,
        )

    generation = profile.get("generation", {})
    expected_generation = {
        "speaker": "female_voice",
        "reference_overrides_speaker": True,
        "cfg_value": 2.0,
        "inference_timesteps": 10,
        "max_len": 2000,
        "retry_badcase": True,
        "candidate_attempts": 3,
        "candidate_cfg_values": [1.8, 2.0, 2.2],
        "segment_unit": "pause-unit",
        "output_sample_rate": 48000,
        "record_seed_when_supported": True,
    }
    for key, expected in expected_generation.items():
        require(generation.get(key) == expected, f"generation.{key} is incorrect", failures)

    pause_policy = profile.get("pause_policy", {})
    require(pause_policy.get("implementation") == "pcm-silence-after-segment-render", "PCM pause implementation is missing", failures)
    require(pause_policy.get("production_pause_authority") == "narration.json[].pause_after_ms", "canonical production pause authority is missing", failures)
    require(pause_policy.get("production_extra_pause_policy") == "optional-pacing-overrides-nonnegative-only", "editorial extra-pause policy is missing", failures)
    require(pause_policy.get("production_gap_defaults_allowed") is False, "profile gap defaults must be forbidden for production", failures)
    require(profile.get("fallback_allowed") is False, "fallback must be forbidden", failures)
    require(ASSEMBLER.is_file(), "PCM narration assembler is missing", failures)
    require(GENERATOR.is_file(), "BlueMagpie API generator is missing", failures)

    if failures:
        for failure in failures:
            print(f"[FAIL] {failure}")
        return 1

    print("[PASS] portable default BlueMagpie-TTS voice profile")
    print("[PASS] exact user-selected 28.32-second mono 48 kHz source FLAC")
    print("[PASS] runtime reference: exact PCM derivative for 4.222125-12.196063 seconds")
    print("[PASS] embedded provenance: BlueMagpieTTS / seed 1150797764 / 40 steps / CFG 2.0")
    print("[PASS] production pause authority: narration.json[].pause_after_ms")
    print("[PASS] local generation entry point: scripts/generate_bluemagpie_tts.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
